pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/sonupathan3613-ui/fastapi-devops.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
 sh 'docker build -t mohammadshareef3613/fastapi-devops:v1 -f app/Dockerfile .'
                    
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        docker.image("mohammadshareef3613/fastapi-devops:v1").push()
                    }
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
                sh 'kubectl apply -f k8s/service.yaml'
            }
        }
    }
}
